name: Trigger Repo2 Workflow

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repo2 Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{secrets.REPOTOKEN}}  # Add the PAT for Repo2
          repository: https://github.com/mubin-puc/devops-test.git  ##Replace with the actual Repo2 details
          event-type: repo2-event-name  # Customize this event name
